export const PROVISIONING_STEPS = [
  "draft",
  "ssh_connecting",
  "host_key_pending",
  "authenticated",
  "discovering",
  "credential_stored",
  "kit_staged",
  "worker_installed",
  "enrollment_issued",
  "paired",
  "service_enabled",
  "heartbeat_seen",
  "smoke_check",
  "ready",
] as const;

export type ProvisioningStep = (typeof PROVISIONING_STEPS)[number];
export type ProvisioningState = ProvisioningStep | "failed";
export type ProvisioningIntent = "continue" | "resume" | "retry" | "rollback" | "remove";
export type ProvisioningAttention = "host_key" | "credential" | "external" | "intent" | null;
export type CredentialState = "pending" | "session_only" | "stored" | "forgotten";
export type SshAuthenticationMethod = "password" | "agent" | "private_key";
export type ServiceScope = "auto" | "user" | "system";
export type AllowedJobKind =
  | "build"
  | "test"
  | "static_analysis"
  | "compute"
  | "gpu"
  | "container"
  | "service"
  | "data_transform"
  | "media_transform"
  | "render";

export interface ProvisioningAdvancedOptions {
  serviceScope: ServiceScope;
  workspace?: string;
  priority: number;
  maximumParallelJobs?: number;
  cpuLimitPercent?: number;
  memoryLimitMiB?: number;
  allowedJobKinds: AllowedJobKind[];
  allowOnBattery: boolean;
}

export interface StartComputerInput {
  /** Stable for retries of one Add Computer submission; generated by the UI. */
  recordId: string;
  /** Stable worker identity paired with recordId for that submission. */
  intendedNodeId: string;
  displayName: string;
  host: string;
  port: number;
  username: string;
  authenticationMethod: SshAuthenticationMethod;
  /** Local controller path; validated natively and omitted unless private_key is selected. */
  privateKeyPath?: string;
  /** Request references are cleared after invocation; JavaScript cannot guarantee physical zeroization. Password auth only. */
  password: string;
  /** Request references are cleared after invocation; JavaScript cannot guarantee physical zeroization. Private-key auth only. */
  passphrase: string;
  rememberPassword: boolean;
  advanced: ProvisioningAdvancedOptions;
}

export interface ProvisioningActionInput {
  id: string;
  revision: number;
  /** Optional replacement for a lost, rejected, or stale SSH password; request references are cleared after invocation. */
  password?: string;
  /** Optional private-key passphrase retry; request references are cleared after invocation. */
  passphrase?: string;
}

export interface ProvisioningHostKey {
  algorithm: string;
  fingerprint: string;
  approved: boolean;
}

export interface ProvisioningFailure {
  code: string;
  retryable: boolean;
  /** Local fixed copy derived from the validated code; never controller-provided text. */
  message: string;
}

export interface ProvisioningInventory {
  hostname: string;
  operatingSystem: string;
  architecture: string;
  cpuModel: string;
  logicalCpuCount: number;
  memoryBytes: number;
  workspaceFreeBytes: number;
  gpuDevices: Array<{ name: string; memoryBytes?: number }>;
  toolchains: Record<string, string>;
}

export interface ProvisioningComputer {
  id: string;
  displayName: string;
  endpoint: { host: string; port: number; username: string };
  state: ProvisioningState;
  step: ProvisioningStep;
  attention: ProvisioningAttention;
  intent: ProvisioningIntent;
  revision: number;
  cycle: number;
  intendedNodeId: string;
  pairedNodeId?: string;
  hostKey?: ProvisioningHostKey;
  inventory?: ProvisioningInventory;
  credential: {
    authenticationMethod: SshAuthenticationMethod;
    rememberRequested: boolean;
    state: CredentialState;
  };
  configuration: ProvisioningAdvancedOptions;
  failure?: ProvisioningFailure;
  createdAt: string;
  updatedAt: string;
}

export interface ProvisioningOperationResult {
  outcome:
    | "checkpoint"
    | "awaiting_host_key_approval"
    | "awaiting_intent"
    | "awaiting_credential"
    | "awaiting_external"
    | "ready"
    | "failed"
    | "rolled_back"
    | "removed";
  computer?: ProvisioningComputer;
  removedId?: string;
}

export type ProvisioningUiAction =
  | "approve_host_key"
  | "continue"
  | "resume"
  | "retry"
  | "repair"
  | "rollback"
  | "remove"
  | "forget_ssh_password";

export class ProvisioningClientError extends Error {
  readonly code: string;
  readonly retryable: boolean;

  constructor(code: string, retryable = false) {
    super(provisioningErrorCopy(code));
    this.name = "ProvisioningClientError";
    this.code = code;
    this.retryable = retryable;
  }
}

function provisioningErrorCopy(code: string): string {
  const messages: Record<string, string> = {
    bridge_unavailable: "The secure desktop provisioning bridge is unavailable.",
    invalid_request: "The computer details are invalid.",
    invalid_id: "The provisioning record identifier is invalid.",
    not_found: "The provisioning record no longer exists.",
    revision_conflict: "This computer changed in another operation. Refresh and try again.",
    host_key_mismatch: "The approved host key does not match the key observed by SSH.",
    credential_required: "Enter the SSH authentication secret again to continue.",
    credential_store_unavailable: "Windows Credential Manager is unavailable for this session.",
    private_key_invalid: "The private-key file is unavailable or failed native path-safety validation.",
    SSH_PRIVATE_KEY_INVALID: "The configured private-key file failed native path-safety validation.",
    SSH_PRIVATE_KEY_UNAVAILABLE: "The configured private-key file is unavailable. Restore it, then retry.",
    SSH_PRIVATE_KEY_REJECTED: "SSH rejected the private-key authentication attempt. Enter the required unlock secret and retry.",
    SSH_AGENT_UNAVAILABLE: "The native SSH agent is unavailable. Start or unlock it, then retry.",
    SSH_AGENT_REJECTED: "SSH rejected every identity offered by the native SSH agent.",
    SSH_AUTH_METHOD_UNSUPPORTED: "The selected SSH authentication method is unavailable in this build.",
    worker_kit_catalog_unavailable: "Managed worker kits are missing or damaged. Repair the desktop installation.",
    controller_unavailable: "The authenticated local controller is unavailable.",
    provisioning_store_unavailable: "The local provisioning database is unavailable.",
    driver_unavailable: "The SSH provisioning driver is unavailable.",
    operation_unavailable: "This action is not valid at the current checkpoint.",
    drive_limit_reached: "Provisioning paused after its bounded work window. Continue to resume.",
    automatic_advance_deadline: "Automatic controller polling reached its ten-minute deadline. Retry to continue.",
    PAIRING_PROVISIONING_FAILED: "Provisioning stopped before the worker completed secure enrollment.",
    PAIRING_WORKER_INSTALL_FAILED: "The worker installation could not be completed before enrollment.",
    PAIRING_WORKER_PAIRING_FAILED: "The worker could not complete secure controller pairing.",
    PAIRING_WORKER_HEALTH_CHECK_FAILED: "The worker did not pass its controller health check.",
    PAIRING_EXPIRED: "The enrollment window expired. Roll back this setup before starting a fresh pairing.",
  };
  return messages[code] ?? "The provisioning operation failed.";
}

function isObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringField(value: Record<string, unknown>, key: string): string {
  const result = value[key];
  if (typeof result !== "string" || result.length === 0) throw new ProvisioningClientError("invalid_response");
  return result;
}

function failureCodeField(value: Record<string, unknown>): string {
  const code = stringField(value, "code");
  if (code.length > 64 || !/^[A-Z0-9_.-]+$/.test(code)) {
    throw new ProvisioningClientError("invalid_response");
  }
  return code;
}

function optionalString(value: Record<string, unknown>, key: string): string | undefined {
  const result = value[key];
  if (result === undefined || result === null) return undefined;
  if (typeof result !== "string" || result.length === 0) throw new ProvisioningClientError("invalid_response");
  return result;
}

function numberField(value: Record<string, unknown>, key: string): number {
  const result = value[key];
  if (typeof result !== "number" || !Number.isSafeInteger(result) || result < 0) {
    throw new ProvisioningClientError("invalid_response");
  }
  return result;
}

function integerField(value: Record<string, unknown>, key: string): number {
  const result = value[key];
  if (typeof result !== "number" || !Number.isSafeInteger(result)) {
    throw new ProvisioningClientError("invalid_response");
  }
  return result;
}

function enumField<T extends string>(value: unknown, allowed: readonly T[]): T {
  if (typeof value !== "string" || !allowed.includes(value as T)) {
    throw new ProvisioningClientError("invalid_response");
  }
  return value as T;
}

function parseAdvanced(value: unknown): ProvisioningAdvancedOptions {
  if (!isObject(value) || !Array.isArray(value.allowedJobKinds)) throw new ProvisioningClientError("invalid_response");
  const serviceScope = enumField(value.serviceScope, ["auto", "user", "system"] as const);
  const allowedJobKinds = value.allowedJobKinds.map((kind) => enumField(kind, [
    "build", "test", "static_analysis", "compute", "gpu", "container", "service",
    "data_transform", "media_transform", "render",
  ] as const));
  const optionalNumber = (key: string) => {
    const item = value[key];
    if (item === undefined || item === null) return undefined;
    if (typeof item !== "number" || !Number.isSafeInteger(item) || item <= 0) throw new ProvisioningClientError("invalid_response");
    return item;
  };
  return {
    serviceScope,
    workspace: optionalString(value, "workspace"),
    priority: integerField(value, "priority"),
    maximumParallelJobs: optionalNumber("maximumParallelJobs"),
    cpuLimitPercent: optionalNumber("cpuLimitPercent"),
    memoryLimitMiB: optionalNumber("memoryLimitMiB"),
    allowedJobKinds,
    allowOnBattery: value.allowOnBattery === true,
  };
}

function parseInventory(value: unknown): ProvisioningInventory | undefined {
  if (value === undefined || value === null) return undefined;
  if (!isObject(value) || !Array.isArray(value.gpuDevices) || !isObject(value.toolchains)) {
    throw new ProvisioningClientError("invalid_response");
  }
  const gpuDevices = value.gpuDevices.map((item) => {
    if (!isObject(item)) throw new ProvisioningClientError("invalid_response");
    const memoryBytes = item.memoryBytes;
    if (memoryBytes !== undefined && (typeof memoryBytes !== "number" || !Number.isSafeInteger(memoryBytes) || memoryBytes < 0)) {
      throw new ProvisioningClientError("invalid_response");
    }
    return { name: stringField(item, "name"), ...(memoryBytes === undefined ? {} : { memoryBytes }) };
  });
  const toolchains: Record<string, string> = {};
  for (const [name, version] of Object.entries(value.toolchains)) {
    if (typeof version !== "string") throw new ProvisioningClientError("invalid_response");
    toolchains[name] = version;
  }
  return {
    hostname: stringField(value, "hostname"),
    operatingSystem: stringField(value, "operatingSystem"),
    architecture: stringField(value, "architecture"),
    cpuModel: stringField(value, "cpuModel"),
    logicalCpuCount: numberField(value, "logicalCpuCount"),
    memoryBytes: numberField(value, "memoryBytes"),
    workspaceFreeBytes: numberField(value, "workspaceFreeBytes"),
    gpuDevices,
    toolchains,
  };
}

export function parseProvisioningComputer(value: unknown): ProvisioningComputer {
  if (!isObject(value) || !isObject(value.endpoint) || !isObject(value.credential)) {
    throw new ProvisioningClientError("invalid_response");
  }
  const state = enumField(value.state, [...PROVISIONING_STEPS, "failed"] as const);
  const step = enumField(value.step, PROVISIONING_STEPS);
  const attention = value.attention === null
    ? null
    : enumField(value.attention, ["host_key", "credential", "external", "intent"] as const);
  let hostKey: ProvisioningHostKey | undefined;
  if (value.hostKey !== undefined && value.hostKey !== null) {
    if (!isObject(value.hostKey) || typeof value.hostKey.approved !== "boolean") throw new ProvisioningClientError("invalid_response");
    hostKey = {
      algorithm: stringField(value.hostKey, "algorithm"),
      fingerprint: stringField(value.hostKey, "fingerprint"),
      approved: value.hostKey.approved,
    };
  }
  let failure: ProvisioningFailure | undefined;
  if (value.failure !== undefined && value.failure !== null) {
    if (!isObject(value.failure) || typeof value.failure.retryable !== "boolean") throw new ProvisioningClientError("invalid_response");
    const keys = Object.keys(value.failure).sort();
    if (keys.length !== 2 || keys[0] !== "code" || keys[1] !== "retryable") {
      throw new ProvisioningClientError("invalid_response");
    }
    const code = failureCodeField(value.failure);
    failure = {
      code,
      retryable: value.failure.retryable,
      message: provisioningErrorCopy(code),
    };
  }
  if ((state === "failed") !== Boolean(failure)) throw new ProvisioningClientError("invalid_response");
  if (state === "failed" && ["SSH_AUTH_REJECTED", "SSH_PRIVATE_KEY_REJECTED"].includes(failure?.code ?? "")) {
    if (failure?.retryable !== true || attention !== "credential") throw new ProvisioningClientError("invalid_response");
  } else if (state === "failed" && attention === "credential") {
    throw new ProvisioningClientError("invalid_response");
  }
  if (typeof value.credential.rememberRequested !== "boolean") throw new ProvisioningClientError("invalid_response");
  const authenticationMethod = value.credential.authenticationMethod === undefined
    ? "password"
    : enumField(value.credential.authenticationMethod, ["password", "agent", "private_key"] as const);
  if (authenticationMethod !== "password" && value.credential.rememberRequested) {
    throw new ProvisioningClientError("invalid_response");
  }
  return {
    id: stringField(value, "id"),
    displayName: stringField(value, "displayName"),
    endpoint: {
      host: stringField(value.endpoint, "host"),
      port: numberField(value.endpoint, "port"),
      username: stringField(value.endpoint, "username"),
    },
    state,
    step,
    attention,
    intent: enumField(value.intent, ["continue", "resume", "retry", "rollback", "remove"] as const),
    revision: numberField(value, "revision"),
    cycle: numberField(value, "cycle"),
    intendedNodeId: stringField(value, "intendedNodeId"),
    pairedNodeId: optionalString(value, "pairedNodeId"),
    hostKey,
    inventory: parseInventory(value.inventory),
    credential: {
      authenticationMethod,
      rememberRequested: value.credential.rememberRequested,
      state: enumField(value.credential.state, ["pending", "session_only", "stored", "forgotten"] as const),
    },
    configuration: parseAdvanced(value.configuration),
    failure,
    createdAt: stringField(value, "createdAt"),
    updatedAt: stringField(value, "updatedAt"),
  };
}

function parseOperation(value: unknown): ProvisioningOperationResult {
  if (!isObject(value)) throw new ProvisioningClientError("invalid_response");
  const outcome = enumField(value.outcome, [
    "checkpoint", "awaiting_host_key_approval", "awaiting_intent", "awaiting_credential",
    "awaiting_external", "ready", "failed", "rolled_back", "removed",
  ] as const);
  const computer = value.computer === undefined || value.computer === null
    ? undefined
    : parseProvisioningComputer(value.computer);
  const removedId = optionalString(value, "removedId");
  if (outcome === "removed" ? !removedId || computer !== undefined : !computer || removedId !== undefined) {
    throw new ProvisioningClientError("invalid_response");
  }
  return { outcome, computer, removedId };
}

function publicError(caught: unknown): ProvisioningClientError {
  if (caught instanceof ProvisioningClientError) return caught;
  if (isObject(caught) && typeof caught.code === "string") {
    return new ProvisioningClientError(caught.code, caught.retryable === true);
  }
  return new ProvisioningClientError("operation_unavailable");
}

function bridge() {
  const result = globalThis.window?.__CLUSTER_YOUR_CODEX__;
  if (!result) throw new ProvisioningClientError("bridge_unavailable");
  return result;
}

function clearAuthenticationSecrets(
  input: { password?: string; passphrase?: string },
  native: { password?: string; passphrase?: string },
): void {
  input.password = "";
  input.passphrase = "";
  native.password = "";
  native.passphrase = "";
}

async function secretAction(
  method: "provisioningContinue" | "provisioningResume" | "provisioningRetry" | "provisioningRepair" | "provisioningRollback" | "provisioningRemove",
  input: ProvisioningActionInput,
): Promise<ProvisioningOperationResult> {
  const native = {
    id: input.id,
    revision: input.revision,
    ...(input.password ? { password: input.password } : {}),
    ...(input.passphrase ? { passphrase: input.passphrase } : {}),
  };
  try {
    return parseOperation(await bridge()[method](native));
  } catch (caught) {
    throw publicError(caught);
  } finally {
    clearAuthenticationSecrets(input, native);
  }
}

export function actionsForProvisioning(computer: ProvisioningComputer): ProvisioningUiAction[] {
  if (computer.state === "ready") {
    return computer.credential.state === "stored"
      && computer.credential.authenticationMethod === "password"
      ? ["forget_ssh_password", "repair", "remove"]
      : ["repair", "remove"];
  }
  if (computer.attention === "host_key" && computer.hostKey && !computer.hostKey.approved) {
    return ["approve_host_key", "rollback", "remove"];
  }
  if (computer.state === "failed") {
    return [
      ...(computer.failure?.retryable ? ["retry" as const] : []),
      "rollback",
      "remove",
    ];
  }
  if (computer.attention === "credential") {
    return computer.intent === "rollback"
      ? ["continue", "remove"]
      : computer.intent === "remove"
        ? ["continue", "rollback"]
        : ["continue", "rollback", "remove"];
  }
  if (computer.attention === "external") {
    return ["continue", "rollback", "remove"];
  }
  return ["resume", "rollback", "remove"];
}

/** A credential-attention checkpoint may expose teardown alternatives. A
 * password retry always requires a replacement; a private-key retry may omit
 * the passphrase when the key is unencrypted or the remote authorization was
 * repaired out of band. */
export function provisioningActionRequiresAuthenticationSecret(
  action: ProvisioningUiAction,
  computer: ProvisioningComputer,
): boolean {
  return computer.attention === "credential"
    && computer.credential.authenticationMethod === "password"
    && (action === "continue" || action === "retry");
}

/** Only controller/worker checkpoints advance unattended. Human trust and
 * secret boundaries always stop the loop. */
export function isAutomaticProvisioningCheckpoint(computer: ProvisioningComputer): boolean {
  return computer.attention === "external"
    && computer.state !== "ready"
    && computer.state !== "failed";
}

export const provisioningClient = {
  async start(input: StartComputerInput): Promise<ProvisioningOperationResult> {
    const native = {
      recordId: input.recordId,
      intendedNodeId: input.intendedNodeId,
      displayName: input.displayName,
      host: input.host,
      port: input.port,
      username: input.username,
      authenticationMethod: input.authenticationMethod,
      ...(input.privateKeyPath ? { privateKeyPath: input.privateKeyPath } : {}),
      ...(input.password ? { password: input.password } : {}),
      ...(input.passphrase ? { passphrase: input.passphrase } : {}),
      rememberPassword: input.rememberPassword,
      advanced: { ...input.advanced, allowedJobKinds: [...input.advanced.allowedJobKinds] },
    };
    try {
      return parseOperation(await bridge().provisioningStart(native));
    } catch (caught) {
      throw publicError(caught);
    } finally {
      clearAuthenticationSecrets(input, native);
    }
  },

  async list(): Promise<ProvisioningComputer[]> {
    try {
      const value = await bridge().provisioningList();
      if (!Array.isArray(value)) throw new ProvisioningClientError("invalid_response");
      return value.map(parseProvisioningComputer);
    } catch (caught) {
      throw publicError(caught);
    }
  },

  async get(id: string): Promise<ProvisioningComputer> {
    try {
      return parseProvisioningComputer(await bridge().provisioningGet({ id }));
    } catch (caught) {
      throw publicError(caught);
    }
  },

  async approveHostKey(computer: ProvisioningComputer): Promise<ProvisioningOperationResult> {
    if (!computer.hostKey || computer.hostKey.approved || computer.attention !== "host_key") {
      throw new ProvisioningClientError("operation_unavailable");
    }
    try {
      return parseOperation(await bridge().provisioningApproveHostKey({
        id: computer.id,
        revision: computer.revision,
        fingerprint: computer.hostKey.fingerprint,
      }));
    } catch (caught) {
      throw publicError(caught);
    }
  },

  continue: (input: ProvisioningActionInput) => secretAction("provisioningContinue", input),
  resume: (input: ProvisioningActionInput) => secretAction("provisioningResume", input),
  retry: (input: ProvisioningActionInput) => secretAction("provisioningRetry", input),
  repair: (input: ProvisioningActionInput) => secretAction("provisioningRepair", input),
  rollback: (input: ProvisioningActionInput) => secretAction("provisioningRollback", input),
  remove: (input: ProvisioningActionInput) => secretAction("provisioningRemove", input),

  async forgetSshPassword(computer: ProvisioningComputer): Promise<ProvisioningOperationResult> {
    try {
      return parseOperation(await bridge().provisioningForgetSshPassword({
        id: computer.id,
        revision: computer.revision,
      }));
    } catch (caught) {
      throw publicError(caught);
    }
  },
};
